# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1d059a79b845eeae9806296bed339782b1de4e078499e0d5b1961b914b1527236f3e97d7d7b8273e738f5ce49a887630e76e4f2c329ca2570a4452e41edc01

test:
  secret_key_base: a72606026aaf1095b4fd219600138b88289572dacc13d005a4fb1d86ee1eb2702695b650c1762f52492984208b1a670136fd9b7f54007ea89a1276374fe6778a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
